# Generated by Django 5.2.10 on 2026-03-24 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario_activo_asignaciontarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignaciontarea',
            options={'ordering': ['-prioridad', 'fecha_asignacion']},
        ),
        migrations.AddField(
            model_name='asignaciontarea',
            name='prioridad',
            field=models.IntegerField(choices=[(1, '🟢 Baja - No urgente'), (2, '🟡 Media - Normal'), (3, '🔴 Alta - Urgente')], default=2, help_text='Nivel de urgencia de la tarea'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TECNICO', 'Técnico'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='usuario_asignado',
            field=models.ForeignKey(limit_choices_to={'activo': True, 'rol': 'TECNICO'}, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_recibidas', to='api.usuario'),
        ),
    ]
