# Generated by Django 5.2.10 on 2026-03-24 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_asignaciontarea_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='usuario_asignado',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_recibidas', to='auth.user'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('ASIGNACION', 'Nueva asignación de tarea'), ('ACTUALIZACION', 'Actualización de tarea'), ('COMPLETADA', 'Tarea completada'), ('CANCELADA', 'Tarea cancelada')], default='ASIGNACION', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.asignaciontarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='auth.user')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
