# Generated by Django 5.2.10 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('api', '0009_alter_usuario_user'),
	]

	operations = [
		migrations.AddField(
			model_name='ticket',
			name='formato_servicio',
			field=models.JSONField(blank=True, default=dict),
		),
	]