# Generated by Django 5.2.10 on 2026-04-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usuario_equipo_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('step', models.CharField(choices=[('ASK_NAME', 'Solicitar nombre'), ('ASK_DEPENDENCIA', 'Solicitar dependencia'), ('ASK_EQUIPMENT', 'Solicitar equipo'), ('ASK_DAMAGE', 'Solicitar tipo de daño'), ('ASK_DESCRIPTION', 'Solicitar descripcion'), ('COMPLETED', 'Completado')], default='ASK_NAME', max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
