# Generated by Django 5.2.10 on 2026-04-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_whatsappconversation_alter_asignaciontarea_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('oficina', models.CharField(max_length=150)),
                ('mejora', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
