# Generated by Django 5.2.10 on 2026-04-12 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_inventarioplaceholder_mantenimientoplaceholder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudreactivacioncontratista',
            name='contratista',
        ),
        migrations.RemoveField(
            model_name='oficinaequipo',
            name='contratista',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='oficina',
        ),
        migrations.RemoveField(
            model_name='oficinaequipo',
            name='funcionario',
        ),
        migrations.AlterModelOptions(
            name='mascotafeedback',
            options={'ordering': ['-fecha'], 'verbose_name': 'Sugerencia', 'verbose_name_plural': 'Sugerencias'},
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Terminada')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FUNCIONARIO', 'Funcionario'), ('CONTRATISTA', 'Contratista')], default='FUNCIONARIO', max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='api.oficina')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='oficinaequipo',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to='api.persona'),
        ),
        migrations.AddField(
            model_name='solicitudreactivacioncontratista',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_reactivacion', to='api.persona'),
        ),
        migrations.DeleteModel(
            name='Contratista',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
