# Generated by Django 5.2.10 on 2026-04-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_consolidate_persona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['nombre'], 'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionarios'},
        ),
    ]
