# Generated by Django 5.2.10 on 2026-04-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_persona_options_delete_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratistaPersona',
            fields=[
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': 'Contratistas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.persona',),
        ),
        migrations.CreateModel(
            name='FuncionarioPersona',
            fields=[
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.persona',),
        ),
    ]
