# Generated by Django 5.2.10 on 2026-04-12 23:25

from django.db import migrations, models


def copy_requester_data_from_usuario(apps, schema_editor):
    Ticket = apps.get_model('api', 'Ticket')
    for ticket in Ticket.objects.select_related('usuario').all():
        usuario = getattr(ticket, 'usuario', None)
        if not usuario:
            continue

        ticket.solicitante_nombre = getattr(usuario, 'nombre', '') or ''
        ticket.solicitante_identificacion = getattr(usuario, 'identificacion', '') or ''
        ticket.solicitante_correo = getattr(usuario, 'correo', '') or ''
        ticket.solicitante_telefono = getattr(usuario, 'telefono', '') or ''
        ticket.save(update_fields=[
            'solicitante_nombre',
            'solicitante_identificacion',
            'solicitante_correo',
            'solicitante_telefono',
        ])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_contratistapersona_funcionariopersona_and_more'),
        ('otros', '0002_delete_usuariootros'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solicitante_correo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solicitante_identificacion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solicitante_nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solicitante_telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(copy_requester_data_from_usuario, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name='ticket',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
