# Generated by Django 5.2.10 on 2026-04-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_solicitudreactivacioncontratista_fecha_nueva_vigencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventarioPlaceholder',
        ),
        migrations.AlterModelOptions(
            name='oficinaequipo',
            options={'ordering': ['oficina__nombre', 'equipo__tipo', 'equipo__serie'], 'verbose_name': 'Asignar equipo', 'verbose_name_plural': 'Equipos asignados'},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', '-fecha'], name='api_ticket_estado_77dc62_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['solicitante_identificacion'], name='api_ticket_solicit_910858_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-fecha'], name='api_ticket_fecha_9a41c9_idx'),
        ),
    ]
