# Generated by Django 5.2.10 on 2026-04-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0018_contratistapersona_funcionariopersona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTareaOtros',
            fields=[
            ],
            options={
                'verbose_name': 'Asignaciones de tarea',
                'verbose_name_plural': 'Asignaciones de tarea',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.asignaciontarea',),
        ),
        migrations.CreateModel(
            name='EquipoOtros',
            fields=[
            ],
            options={
                'verbose_name': 'Equipos',
                'verbose_name_plural': 'Equipos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.equipo',),
        ),
        migrations.CreateModel(
            name='TicketOtros',
            fields=[
            ],
            options={
                'verbose_name': 'Tickets',
                'verbose_name_plural': 'Tickets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.ticket',),
        ),
        migrations.CreateModel(
            name='UsuarioOtros',
            fields=[
            ],
            options={
                'verbose_name': 'Usuarios',
                'verbose_name_plural': 'Usuarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.usuario',),
        ),
    ]
