# Generated by Django 5.2.10 on 2026-04-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioOtros',
        ),
    ]
