# Generated by Django 5.2.10 on 2026-04-13 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0020_solicitudreactivacioncontratista_fecha_nueva_vigencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=120)),
                ('producto', models.CharField(max_length=160)),
                ('marca', models.CharField(blank=True, default='', max_length=80)),
                ('modelo', models.CharField(blank=True, default='', max_length=80)),
                ('referencia_fabricante', models.CharField(blank=True, default='', max_length=120)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=120)),
                ('placa_interna', models.CharField(blank=True, default='', max_length=80)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=120)),
                ('ubicacion_actual', models.CharField(blank=True, default='', max_length=120)),
                ('cantidad_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ultima_entrada', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_salida', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'ordering': ['categoria', 'tipo', 'producto', 'numero_serie'],
            },
        ),
        migrations.CreateModel(
            name='SalidaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('motivo', models.CharField(choices=[('INSTALACION', 'Instalación'), ('TRASLADO', 'Traslado'), ('PRESTAMO', 'Préstamo'), ('BAJA', 'Baja por daño'), ('EXTRAVIADO', 'Extraviado')], default='INSTALACION', max_length=20)),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('tecnico_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('tecnico_usuario', models.CharField(blank=True, default='', max_length=150)),
                ('funcionario_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('funcionario_identificacion', models.CharField(blank=True, default='', max_length=50)),
                ('funcionario_tipo', models.CharField(blank=True, default='', max_length=30)),
                ('firma_tecnico_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('firma_funcionario_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('acta_pdf', models.FileField(blank=True, null=True, upload_to='inventario/actas/')),
                ('stock_aplicado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('funcionario_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_inventario', to='api.persona')),
                ('oficina_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_inventario', to='api.oficina')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_registradas', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='inventario.stockinventario')),
                ('tecnico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_tecnicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='IngresoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('REMISION', 'Remisión'), ('ORDEN_COMPRA', 'Orden de compra'), ('ACTA_DONACION', 'Acta de donación'), ('OTRO', 'Otro')], default='FACTURA', max_length=20)),
                ('numero_documento', models.CharField(blank=True, default='', max_length=80)),
                ('proveedor', models.CharField(blank=True, default='', max_length=150)),
                ('orden_compra', models.CharField(blank=True, default='', max_length=80)),
                ('guia_remision', models.CharField(blank=True, default='', max_length=80)),
                ('area_receptora', models.CharField(blank=True, default='', max_length=120)),
                ('categoria_producto', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_producto', models.CharField(blank=True, default='', max_length=120)),
                ('producto_nombre', models.CharField(blank=True, default='', max_length=160)),
                ('marca', models.CharField(blank=True, default='', max_length=80)),
                ('modelo', models.CharField(blank=True, default='', max_length=80)),
                ('referencia_fabricante', models.CharField(blank=True, default='', max_length=120)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=120)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=120)),
                ('placa_interna', models.CharField(blank=True, default='', max_length=80)),
                ('lote', models.CharField(blank=True, default='', max_length=80)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado_recepcion', models.CharField(choices=[('NUEVO', 'Nuevo'), ('BUEN_ESTADO', 'Buen estado'), ('CON_OBSERVACION', 'Con observación'), ('DEFECTUOSO', 'Defectuoso')], default='NUEVO', max_length=20)),
                ('ubicacion_inicial', models.CharField(blank=True, default='', max_length=120)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('stock_aplicado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('oficina_receptora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_inventario', to='api.oficina')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='inventario.stockinventario')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha_entrada'],
            },
        ),
    ]
