# Generated by Django 5.2.10 on 2026-04-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_ingreso_stock_nullable_and_drop_unused_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoinventario',
            name='vencimiento_no_aplica',
            field=models.BooleanField(default=False),
        ),
    ]
