# Generated by Django 5.2.10 on 2026-04-13 19:35

import django.db.models.deletion
from django.db import migrations, models


def backfill_categoria_catalogo(apps, schema_editor):
    CategoriaInventario = apps.get_model('inventario', 'CategoriaInventario')
    StockInventario = apps.get_model('inventario', 'StockInventario')
    IngresoInventario = apps.get_model('inventario', 'IngresoInventario')

    categorias_map = {}

    for stock in StockInventario.objects.all().only('id', 'categoria'):
        nombre = (stock.categoria or '').strip()
        if not nombre:
            continue
        categoria_obj = categorias_map.get(nombre)
        if categoria_obj is None:
            categoria_obj, _ = CategoriaInventario.objects.get_or_create(nombre=nombre, defaults={'activa': True})
            categorias_map[nombre] = categoria_obj
        StockInventario.objects.filter(pk=stock.pk).update(categoria_catalogo_id=categoria_obj.id)

    for ingreso in IngresoInventario.objects.all().only('id', 'categoria_producto'):
        nombre = (ingreso.categoria_producto or '').strip()
        if not nombre:
            continue
        categoria_obj = categorias_map.get(nombre)
        if categoria_obj is None:
            categoria_obj, _ = CategoriaInventario.objects.get_or_create(nombre=nombre, defaults={'activa': True})
            categorias_map[nombre] = categoria_obj
        IngresoInventario.objects.filter(pk=ingreso.pk).update(categoria_catalogo_id=categoria_obj.id)


def reverse_backfill_categoria_catalogo(apps, schema_editor):
    # Preserve created catalog entries on rollback of data migration.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_ingresoinventario_vencimiento_no_aplica'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de inventario',
                'verbose_name_plural': 'Categorías de inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ingresoinventario',
            name='categoria_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='inventario.categoriainventario'),
        ),
        migrations.AddField(
            model_name='stockinventario',
            name='categoria_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='inventario.categoriainventario'),
        ),
        migrations.RunPython(backfill_categoria_catalogo, reverse_backfill_categoria_catalogo),
    ]
