# Generated by Django 5.2.10 on 2026-04-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_stock_categoria_optional_remove_ingreso_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockinventario',
            options={'ordering': ['tipo', 'producto', 'referencia_fabricante'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stock'},
        ),
        migrations.AlterField(
            model_name='ingresoinventario',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='inventario.stockinventario'),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='inventario.stockinventario'),
        ),
    ]
